### ISSUE TITLE
Derpy Mule

### ISSUE THREAD

**Issue by tb1** [Demiurge-DSP/feedback-and-info#17]
**Feedback or issue :**  

A few days ago, one of my mules got a little derpy when zoning.  He wouldn't load into zone ("Downloading data..."), and another mule got stuck in position (this likely was some weird multisend thing, and can be ignored).

I did the standard thing, kill off the derpy mules, relog them in, and continue playing.  The problem is, the mule Med is now consistently derpy.

- When logged in, it shows his HP bar twice.  This goes away when he joins a party.
- He can not use <bt> macros or the client will crash.
- This only happens on Med.
- The ashita configs for Ked, Led, Med and Ned are the same other than username/password and initial screen position.

Normally I'd chalk this up to my install being corrupt, or some odd shit on my machine, or maybe hardware problems, but this is too consistent to be that.

If it is just a transient thing you think will go away when the server restarts, that's fine and I can wait until next update.  However, if you suspect it some sort of persistant issue (eg. database issue), I figure I'd make you aware of it so it doesn't spread/affect other people.

![med](https://user-images.githubusercontent.com/3310503/36913986-f5791804-1e08-11e8-9f8c-3d3d76f32e1a.png)

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**

**Comment by TeoTwawki** [comment]
Have seen a plugin do this..I forget which one. I'll try and find that. It sounds weird because you'd think "well all my alts use the same ones though! that's impossible!" but no really, have witnessed. I have no explanation for how it only hit 1 alt either. The upside is its super easy to rule out : log effected char in alone using only xiloader without windower or ashita. Still screwy? then its server side!

Another possibility is game thinks he's in a party with himself. have seen it in rare cases and it always went away after I cleared the sessions and parties during maint.

**Comment by TeoTwawki** [comment]
Is he normal now?

**Comment by TeoTwawki** [comment]
never got an answer. if still happening you can go ahead and catch me on discord.
